language: rust

branches:
  only: master

script: rustc -V

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  on:
    branch: master
    
notifications:
  email: false
