language: rust

branches:
  except: /.*/

script: rustc -V

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
    
notifications:
  email: false
